### ISSUE TITLE
`dedent` and template tag functions

### ISSUE THREAD

**Issue by rauschma** [dmnd/dedent#11]
Possibly interesting for the future (but I don’t have a use case for it, myself): allow `dedent` to be combined with template tag functions:

```js
console.log(dedent(html)`
    <div>
    Hello!
    </div>
`);
```

However, things would be relatively complex, because you’d want to dedent before passing the input on to the tag function.

**Comment by JoshuaKGoldberg** [comment]
👋 It's been quite a few years since this was posted and the only reactions have been a couple of 👍s. Closing it out for housekeeping.

If anybody wants to file a new feature request, please do. Some more details on what how it would behave would be good.

Note that `dedent` does support being called as a function (`dedent('\n text')`) or a template tag literal (<code>dedent\`\n text\`</code>).

Cheers!
