### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by andywer** [dmnd/dedent#16]
The ES6 default export is a good thing, but hasn't been published yet.

Could you please `npm version` & `npm publish`?

**Comment by JoshuaKGoldberg** [comment]
I bumped the version in `package.json` to `0.8.0-beta` in 6e18137. @dmnd is working on getting me publish rights so I can release it as a beta. Hoping to get this out soon! 🤞

**Comment by JoshuaKGoldberg** [comment]
OK! Thanks to @dmnd - I now have npm access. Since there were some big changes (#32) I bumped up to a 1.0.0 and have published [`dedent@1.0.0`](https://www.npmjs.com/package/dedent/v/1.0.0) under the _`beta`_ tag. 🎉

Let's allow the beta 1.0 to settle for a week just in case. I'll promote it to stable in a week.

**Comment by JoshuaKGoldberg** [comment]
Ok, it's been a week. [`dedent@1.0.1`](https://www.npmjs.com/package/dedent/v/1.0.1) is published (#42). Closing this issue out - cheers!
