### ISSUE TITLE
Newline issue

### ISSUE THREAD

**Issue by jasonkuhrt** [dmnd/dedent#34]
Started here https://github.com/indentjs/endent/issues/8

More details here https://github.com/prisma/nexus-prisma/issues/50

The issue is that if `\n` shows up in a template string it gets read as a newline.

**Comment by JoshuaKGoldberg** [comment]
There's a lot of text to read through in those two linked issues & their linked issues, and I lost track of where the problem is in this `dedent` specifically. Could you/someone please post a concrete example of using `dedent` in a way that shows the bug - including expected & actual outputs for some input?

This _might_ be related to / even a duplicate of #22.

**Comment by JoshuaKGoldberg** [comment]
Character escaping logic was reworked a bit in #2 / #45 / #46 / #65. Since this one has been sitting for a bit and _might_ be a dup of #12, closing out to keep the issue queue small. Please let me know if that's wrong! ❤️

**Comment by adamsol** [comment]
> Since this one has been sitting for a bit and might be a dup of #12, closing out to keep the issue queue small. Please let me know if that's wrong!

It looks like the originally reported issue with escaped newlines still persists, and the `alignValues` option from #12 doesn't change anything.

Expected:

```
dedent`\\n` === `\\n`
```

Current behavior:

```
dedent`\\n` === `\\\n`
```

My actual use case was something like:

```
const json = JSON.stringify({ a: 'multi\nline' });
console.log(json);
console.log(dedent`${json}`);
```

which outputs:

```
{"a":"multi\nline"}
{"a":"multi
line"}
```

The second JSON is invalid and cannot be parsed back.
